### ISSUE TITLE
Let you know about similar projects

### ISSUE THREAD

**Issue by Nicolas-Bouteille** [drupal-fancy/fancy_features#7]
https://www.drupal.org/node/2227265

**Comment by yannickoo** [comment]
Thank you for sharing :)

**Comment by Nicolas-Bouteille** [comment]
yep! Love that kind of projects. I've been waiting for that kind of project to happen, discovered Nestedbox first, then Paragraphs and now yours... would love to see all of you guys collaborate into something awesome. I might join forces at a time, but I gotta gain some XP first ^^
